/*asiento 14 y fila 2 Hector Rolando Rivera Varela
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenlab10p2_hectorrivera;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hriverav
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        try {
            File file = new File("./Bond - Victory [TubeRipper.cc].wav");
            AudioInputStream audio = AudioSystem.getAudioInputStream(file);
            Clip clip = AudioSystem.getClip();
            clip.open(audio);
            clip.start();
            clip.loop(-1);
        } catch (Exception e) {
            e.printStackTrace();
        }

        binario.readFile();
        loadJcombo();
        binario.addtoFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_CreateAuto = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jTextField_marca = new javax.swing.JTextField();
        jTextField_modelo = new javax.swing.JTextField();
        jButton_crear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner_velocidad = new javax.swing.JSpinner();
        jPanel_principal = new javax.swing.JPanel();
        jButton_showCrear = new javax.swing.JButton();
        jLabel_p1_modelo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_p1_marca = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_p1_velocidad = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_p2_modelo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_p2_marca = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel_p2_velocidad = new javax.swing.JLabel();
        jButton_startsim = new javax.swing.JButton();
        jComboBox_p1 = new javax.swing.JComboBox<>();
        jComboBox_p2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jDialog_CreateAuto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 340, -1));
        jPanel1.add(jTextField_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 340, -1));

        jButton_crear.setText("Crear");
        jButton_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_crearMouseClicked(evt);
            }
        });
        jPanel1.add(jButton_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 100, -1));

        jLabel1.setText("Velocidad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setText("Marca");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel6.setText("modelo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jSpinner_velocidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));
        jPanel1.add(jSpinner_velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 220, -1));

        jDialog_CreateAuto.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_showCrear.setText("Crear Auto");
        jButton_showCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_showCrearMouseClicked(evt);
            }
        });

        jLabel_p1_modelo.setText("-");

        jLabel2.setText("modelo");

        jLabel3.setText("marca");

        jLabel_p1_marca.setText("-");

        jLabel5.setText("velocidad");

        jLabel_p1_velocidad.setText("-");

        jLabel7.setText("modelo");

        jLabel_p2_modelo.setText("-");

        jLabel9.setText("marca");

        jLabel_p2_marca.setText("-");

        jLabel11.setText("velocidad");

        jLabel_p2_velocidad.setText("-");

        jButton_startsim.setText("Start");
        jButton_startsim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_startsimMouseClicked(evt);
            }
        });

        jComboBox_p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_p1ActionPerformed(evt);
            }
        });

        jComboBox_p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_p2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Jugador 1");

        jLabel14.setText("Jugador 2");

        jLabel15.setText("Partida");

        javax.swing.GroupLayout jPanel_principalLayout = new javax.swing.GroupLayout(jPanel_principal);
        jPanel_principal.setLayout(jPanel_principalLayout);
        jPanel_principalLayout.setHorizontalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addComponent(jButton_startsim, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_p1_velocidad)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel_p1_marca)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel_p1_modelo)
                                    .addComponent(jComboBox_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_principalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addGap(48, 48, 48)))
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_showCrear, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_principalLayout.createSequentialGroup()
                                    .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_p2_velocidad)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel_p2_marca)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel_p2_modelo))
                                    .addGap(83, 83, 83)))
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jComboBox_p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)))))
                .addContainerGap())
        );
        jPanel_principalLayout.setVerticalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addComponent(jButton_showCrear)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_principalLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_p1_modelo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_p1_marca)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_p1_velocidad))
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_p2_modelo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_p2_marca)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_p2_velocidad)))
                .addGap(31, 31, 31)
                .addComponent(jButton_startsim)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_crearMouseClicked
        // TODO add your handling code here:
        try {
            binario.readFile();
        } catch (Exception e) {
        }
        int speed = (Integer) jSpinner_velocidad.getValue();
        binario.addAutos(new Auto(jTextField_marca.getText(), jTextField_modelo.getText(), speed));
        JOptionPane.showMessageDialog(jDialog_CreateAuto, "se creo su auto");
        loadJcombo();
        try {
            binario.addtoFile();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_crearMouseClicked

    private void jButton_showCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_showCrearMouseClicked
        // TODO add your handling code here:
        jDialog_CreateAuto.pack();
        jDialog_CreateAuto.setVisible(true);
    }//GEN-LAST:event_jButton_showCrearMouseClicked

    private void jButton_startsimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_startsimMouseClicked
        // TODO add your handling code here:
        if (p1 != null && p2 != null) {
            this.setVisible(false);

        }


    }//GEN-LAST:event_jButton_startsimMouseClicked

    private void jComboBox_p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_p1ActionPerformed
        // TODO add your handling code here:
        try {
            binario.readFile();
        } catch (Exception e) {
        }
        try {
            p1 = binario.getAutos().get(jComboBox_p1.getSelectedIndex());
            jLabel_p1_marca.setText(p1.getMarca());
            jLabel_p1_modelo.setText(p1.getModelo());
            jLabel_p1_velocidad.setText(p1.getVelocidad() + "");
        } catch (Exception e) {

        }
        try {
            binario.addtoFile();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox_p1ActionPerformed

    private void jComboBox_p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_p2ActionPerformed
        // TODO add your handling code here:
        try {
            binario.readFile();
        } catch (Exception e) {
        }
        try {
            p2 = binario.getAutos().get(jComboBox_p2.getSelectedIndex());
            jLabel_p2_marca.setText(p2.getMarca());
            jLabel_p2_modelo.setText(p2.getModelo());
            jLabel_p2_velocidad.setText(p2.getVelocidad() + "");
        } catch (Exception e) {

        }

        try {
            binario.addtoFile();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox_p2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_crear;
    private javax.swing.JButton jButton_showCrear;
    private javax.swing.JButton jButton_startsim;
    private javax.swing.JComboBox<String> jComboBox_p1;
    private javax.swing.JComboBox<String> jComboBox_p2;
    private javax.swing.JDialog jDialog_CreateAuto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_p1_marca;
    private javax.swing.JLabel jLabel_p1_modelo;
    private javax.swing.JLabel jLabel_p1_velocidad;
    private javax.swing.JLabel jLabel_p2_marca;
    private javax.swing.JLabel jLabel_p2_modelo;
    private javax.swing.JLabel jLabel_p2_velocidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_principal;
    private javax.swing.JSpinner jSpinner_velocidad;
    private javax.swing.JTextField jTextField_marca;
    private javax.swing.JTextField jTextField_modelo;
    // End of variables declaration//GEN-END:variables
    AdminAutos binario = new AdminAutos("./si.si");
    Auto p1 = null;
    Auto p2 = null;

    public void loadJcombo() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox_p1.getModel();
        model.removeAllElements();
        for (Auto auto : binario.getAutos()) {
            model.addElement(auto.getMarca() + " " + auto.getModelo());
        }
        jComboBox_p1.setModel(model);
        jComboBox_p2.setModel(model);
    }
}
